# fly.toml app configuration file generated for agente-de-pruevas on 2026-10-07T03:25:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agente-de-pruevas'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  OLLAMA_HOST = '127.0.0.1:11434'
  OLLAMA_KEEP_ALIVE = '5m'
  OLLAMA_MODEL = 'qwen2.5:3b'
  PORT = '8080'
  PULL_MODEL = 'true'

[[mounts]]
  source = 'ollama_models'
  destination = '/root/.ollama'
  initial_size = '20gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '4096mb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
